services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
    networks:
      - app-network

  node:
    container_name: node-app
    build:
      context: ./app
      dockerfile: Dockerfile
    image: jpbecker/node
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=nodedb

    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network
  
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: